### ISSUE TITLE
cross-python build 44 is buggy

### ISSUE THREAD

**Issue by beckermr** [conda-forge/cross-python-feedstock#82]
Now I see fun new errors for cross-python build 44:

```
2024-09-26T03:07:03.1250216Z Setting up cross-python
2024-09-26T03:07:03.2437393Z ERROR: [Errno 2] No such file or directory: '/home/conda/feedstock_root/build_artifacts/conda-forge-ci-setup_1727319872190/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.12/.py'
2024-09-26T03:07:04.7163121Z Traceback (most recent call last):
2024-09-26T03:07:04.7167198Z   File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2555, in build
2024-09-26T03:07:04.7174911Z     utils.check_call_env(
2024-09-26T03:07:04.7175879Z   File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 404, in check_call_env
2024-09-26T03:07:04.7180666Z     return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
2024-09-26T03:07:04.7183451Z   File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
2024-09-26T03:07:04.7183794Z     raise subprocess.CalledProcessError(proc.returncode, _args)
2024-09-26T03:07:04.7184321Z subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/conda/feedstock_root/build_artifacts/conda-forge-ci-setup_1727319872190/work/conda_build.sh']' returned non-zero exit status 1.
```

job link is here: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1037765&view=logs&j=8c2cc4aa-48d5-5391-2898-bd1709641f14&t=5a374fee-58a1-53ad-1500-8ede64abe688

@conda-forge/cross-python @isuruf @jakirkham

**Comment by beckermr** [comment]
xref: https://github.com/conda-forge/cross-python-feedstock/pull/81

**Comment by jakirkham** [comment]
Could it be that `${_CONDA_PYTHON_SYSCONFIGDATA_NAME}` is undefined leading `sysconfigdata_fn` to become a reference to `.py` only ?

https://github.com/conda-forge/cross-python-feedstock/blob/3fa288478bf517de4e74931b8d12f996bff7de46/recipe/activate-cross-python.sh#L15-L16

If so, wonder if the `--sysconfig-data` parameter...

https://github.com/conda-forge/cross-python-feedstock/blob/3fa288478bf517de4e74931b8d12f996bff7de46/recipe/activate-cross-python.sh#L39

...can receive similar treatment to `CONDA_BUILD_SYSROOT`

https://github.com/conda-forge/cross-python-feedstock/blob/3fa288478bf517de4e74931b8d12f996bff7de46/recipe/activate-cross-python.sh#L33-L37
