### ISSUE TITLE
[Regression] No such file or directory: _sysconfigdata_aarch64_conda_cos7_linux_gnu.py

### ISSUE THREAD

**Issue by mxschmitt** [conda-forge/cross-python-feedstock#93]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Bisected to the following:

Bad `conda install cross-python_linux-aarch64=3.12=48_cpython`
Good `conda install cross-python_linux-aarch64=3.12=47_cpython`

Looks like 6c4a157dcf66b2f8181b4a3e5c1066644469b270 is the commit which caused it.

Looks also like that between 48 and 50 the error has changed slightly.

Repro steps under Linux (Ubuntu):

```
git clone https://github.com/microsoft/playwright-python
cd playwright-python
conda install anaconda-client conda-build conda-verify
conda install cross-python_linux-aarch64
conda build --user microsoft . -m conda_build_config_linux_aarch64.yaml
```

### Installed packages

```
@mxschmitt ➜ ~/playwright-python (main) $ conda list
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
anaconda-client           1.12.3             pyhd8ed1ab_1    conda-forge
archspec                  0.2.3              pyhd3eb1b0_0  
attrs                     24.2.0          py312h06a4308_0  
backports                 1.1                pyhd3eb1b0_1  
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0  
backports.tempfile        1.0                pyhd3eb1b0_1  
backports.weakref         1.0.post1                  py_1  
beautifulsoup4            4.12.3          py312h06a4308_0  
binutils_impl_linux-64    2.43                 h4bf12b8_2    conda-forge
binutils_impl_linux-aarch64 2.43                 h15a6ed9_2    conda-forge
binutils_linux-aarch64    2.43                 h7726a90_2    conda-forge
boltons                   23.0.0          py312h06a4308_0  
brotli-python             1.0.9           py312h6a678d5_8  
bzip2                     1.0.8                h5eee18b_6  
c-ares                    1.19.1               h5eee18b_0  
ca-certificates           2024.9.24            h06a4308_0  
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py312h5eee18b_1  
chardet                   4.0.0           py312h06a4308_1003  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.7           py312h06a4308_0  
conda                     24.1.2          py312h7900ff3_0    conda-forge
conda-build               24.1.2          py312h06a4308_0  
conda-index               0.5.0           py312h06a4308_0  
conda-libmamba-solver     24.1.0             pyhd3eb1b0_0  
conda-package-handling    2.2.0           py312h06a4308_1  
conda-package-streaming   0.9.0           py312h06a4308_0  
conda-verify              3.4.2                      py_1  
cross-python_linux-aarch64 3.12                 48_cpython    conda-forge
crossenv                  1.5.0              pyhd8ed1ab_1    conda-forge
cryptography              41.0.4                   pypi_0    pypi
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distro                    1.9.0           py312h06a4308_0  
expat                     2.6.2                h6a678d5_0  
filelock                  3.13.1          py312h06a4308_0  
fmt                       9.1.0                hdb19cb5_1  
frozendict                2.4.2           py312h06a4308_0  
future                    1.0.0           py312h06a4308_0  
gcc_impl_linux-64         14.2.0               h6b349bd_1    conda-forge
gcc_impl_linux-aarch64    14.2.0               hfe1696b_1    conda-forge
gcc_linux-aarch64         14.2.0               h476b46d_5    conda-forge
gxx_impl_linux-aarch64    14.2.0               h0a8fb04_1    conda-forge
icu                       73.1                 h6a678d5_0  
idna                      3.7             py312h06a4308_0  
jinja2                    3.1.4           py312h06a4308_1  
jsonpatch                 1.33            py312h06a4308_1  
jsonpointer               2.1                pyhd3eb1b0_0  
jsonschema                4.23.0          py312h06a4308_0  
jsonschema-specifications 2023.7.1        py312h06a4308_0  
jupyter_core              5.7.2              pyh31011fe_1    conda-forge
kernel-headers_linux-64   3.10.0              he073ed8_18    conda-forge
kernel-headers_linux-aarch64 4.18.0              h05a177a_18    conda-forge
krb5                      1.20.1               h143b758_1  
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
ld_impl_linux-aarch64     2.43                 h0a21ee1_2    conda-forge
libarchive                3.6.2                h6ac8c49_3  
libcurl                   8.7.1                h251f7ec_0  
libedit                   3.1.20230828         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.4                h6a678d5_1  
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-devel_linux-64     14.2.0             h41c2201_101    conda-forge
libgcc-devel_linux-aarch64 14.2.0               h3d07465_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblief                   0.12.3               h6a678d5_0  
libmamba                  1.5.8                hfe524e5_2  
libmambapy                1.5.8           py312h2dafd23_2  
libnghttp2                1.57.0               h2d74bed_0  
libnsl                    2.0.1                hd590300_0    conda-forge
libsanitizer              14.2.0               h2a3dede_1    conda-forge
libsolv                   0.7.24               he621ea3_1  
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.11.0               h251f7ec_0  
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-devel_linux-aarch64 14.2.0               h3d07465_1    conda-forge
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.10.4               hfdd30dd_2  
libzlib                   1.2.13               h4ab18f5_6    conda-forge
lz4-c                     1.9.4                h6a678d5_1  
markupsafe                2.1.3           py312h5eee18b_0  
menuinst                  2.0.2           py312h06a4308_1  
more-itertools            10.3.0          py312h06a4308_0  
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h6a678d5_0  
openssl                   3.3.2                hb9d3cd8_0    conda-forge
packaging                 23.2            py312h06a4308_0  
patch                     2.7.6             h7b6447c_1001  
patchelf                  0.17.2               h6a678d5_0  
pcre2                     10.42                hebb0a14_1  
pip                       24.2                     pypi_0    pypi
pkginfo                   1.10.0          py312h06a4308_0  
platformdirs              3.10.0          py312h06a4308_0  
pluggy                    1.0.0           py312h06a4308_1  
popt                      1.16              h0b475e3_2002    conda-forge
psutil                    5.9.0           py312h5eee18b_0  
py-lief                   0.12.3          py312h6a678d5_0  
pybind11-abi              5                    hd3eb1b0_0  
pycosat                   0.6.6           py312h5eee18b_1  
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 24.2.1          py312h06a4308_0  
pysocks                   1.7.1           py312h06a4308_0  
python                    3.12.2          hab00c5b_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    conda-forge
python-libarchive-c       5.1                pyhd3eb1b0_0  
python_abi                3.12                    5_cp312    conda-forge
pytz                      2024.1          py312h06a4308_0  
pyyaml                    6.0.2           py312h5eee18b_0  
readline                  8.2                  h5eee18b_0  
referencing               0.30.2          py312h06a4308_0  
reproc                    14.2.4               h6a678d5_2  
reproc-cpp                14.2.4               h6a678d5_2  
requests                  2.31.0          py312h06a4308_1  
requests-toolbelt         1.0.0              pyhd8ed1ab_0    conda-forge
rpds-py                   0.10.6          py312hb02cf49_0  
rsync                     3.3.0                he6cb5fe_0    conda-forge
ruamel.yaml               0.17.21         py312h5eee18b_0  
sed                       4.8                  he412f7d_0    conda-forge
setuptools                69.5.1          py312h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
soupsieve                 2.5             py312h06a4308_0  
sqlite                    3.45.3               h5eee18b_0  
sysroot_linux-64          2.17                h4a8ded7_18    conda-forge
sysroot_linux-aarch64     2.17                h5b4a56d_18    conda-forge
tk                        8.6.14               h39e8969_0  
tqdm                      4.66.2          py312he106c6f_0  
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
truststore                0.8.0           py312h06a4308_0  
tzdata                    2024a                h04d1e81_0  
urllib3                   1.26.18         py312h06a4308_0  
wheel                     0.43.0          py312h06a4308_0  
xxhash                    0.8.2                hd590300_0    conda-forge
xz                        5.4.6                h5eee18b_1  
yaml                      0.2.5                h7b6447c_0  
yaml-cpp                  0.8.0                h6a678d5_1  
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstandard                 0.22.0          py312h2c38b39_0  
zstd                      1.5.5                hc292b87_2  
```

### Environment info

```
@mxschmitt ➜ ~/playwright-python (main) $ conda info

     active environment : None
       user config file : /home/codespace/.condarc
 populated config files : /home/codespace/.condarc
          conda version : 24.1.2
    conda-build version : 24.1.2
         python version : 3.12.2.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=24.1.2=0
                          __glibc=2.31=0
                          __linux=6.5.0=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/microsoft/linux-64
                          https://conda.anaconda.org/microsoft/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/codespace/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/codespace/.conda/envs
               platform : linux-64
             user-agent : conda/24.1.2 requests/2.32.3 CPython/3.12.2 Linux/6.5.0-1025-azure ubuntu/20.04.6 glibc/2.31 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

##### Logs

````
Full error: 

```
@mxschmitt ➜ ~/playwright-python (main) $ conda build --user microsoft . -m conda_build_config_linux_aarch64.yaml
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.26
Copying /home/codespace/playwright-python to /opt/conda/conda-bld/playwright_1730983595220/work/
Adding in variants from internal_defaults
Adding in variants from /home/codespace/playwright-python/conda_build_config_linux_aarch64.yaml
Attempting to finalize metadata for playwright
Reloading output folder (local): ...working... done
Getting pinned dependencies: ...working... done
Reloading output folder: ...working... done
Getting pinned dependencies: ...working... done
Reloading output folder: ...working... done
Getting pinned dependencies: ...working... done
BUILD START: ['playwright-1.48.0-py313_0.tar.bz2']
Channels:
 - local
 - microsoft
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda/conda-bld/playwright_1730983595220/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl


The following NEW packages will be INSTALLED:

    _openmp_mutex:         4.5-2_gnu                 conda-forge
    bzip2:                 1.0.8-h68df207_7          conda-forge
    c-ares:                1.34.2-ha64f414_0         conda-forge
    ca-certificates:       2024.8.30-hcefe29a_0      conda-forge
    curl:                  8.11.0-h3ec0cbf_0         conda-forge
    keyutils:              1.6.1-h4e544f5_0          conda-forge
    krb5:                  1.21.3-h50a48e9_0         conda-forge
    ld_impl_linux-aarch64: 2.43-h80caac9_2           conda-forge
    libcurl:               8.11.0-h3ec0cbf_0         conda-forge
    libedit:               3.1.20191231-he28a2e2_2   conda-forge
    libev:                 4.33-h31becfc_2           conda-forge
    libexpat:              2.6.4-h5ad3122_0          conda-forge
    libffi:                3.4.2-h3557bc0_5          conda-forge
    libgcc:                14.2.0-he277a41_1         conda-forge
    libgcc-ng:             14.2.0-he9431aa_1         conda-forge
    libgomp:               14.2.0-he277a41_1         conda-forge
    libmpdec:              4.0.0-h68df207_0          conda-forge
    libnghttp2:            1.64.0-hc8609a4_0         conda-forge
    libsqlite:             3.47.0-hc4a20ef_1         conda-forge
    libssh2:               1.11.0-h492db2e_0         conda-forge
    libstdcxx:             14.2.0-h3f4de04_1         conda-forge
    libstdcxx-ng:          14.2.0-hf1166c9_1         conda-forge
    libuuid:               2.38.1-hb4cce97_0         conda-forge
    libzlib:               1.3.1-h86ecc28_2          conda-forge
    ncurses:               6.5-hcccb83c_1            conda-forge
    openssl:               3.3.2-h86ecc28_0          conda-forge
    packaging:             24.1-pyhd8ed1ab_0         conda-forge
    pip:                   24.3.1-pyh145f28c_0       conda-forge
    python:                3.13.0-h6bfe66a_100_cp313 conda-forge
    python_abi:            3.13-5_cp313              conda-forge
    readline:              8.2-h8fc344f_1            conda-forge
    setuptools:            75.3.0-pyhd8ed1ab_0       conda-forge
    setuptools-scm:        8.1.0-pyhd8ed1ab_0        conda-forge
    setuptools_scm:        8.1.0-hd8ed1ab_0          conda-forge
    tk:                    8.6.13-h194ca79_0         conda-forge
    tomli:                 2.0.2-pyhd8ed1ab_0        conda-forge
    typing-extensions:     4.12.2-hd8ed1ab_0         conda-forge
    typing_extensions:     4.12.2-pyha770c72_0       conda-forge
    tzdata:                2024b-hc8b5060_0          conda-forge
    wheel:                 0.44.0-pyhd8ed1ab_0       conda-forge
    xz:                    5.2.6-h9cdd2b7_0          conda-forge
    zstd:                  1.5.6-h02f22dd_0          conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Channels:
 - local
 - microsoft
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Channels:
 - local
 - microsoft
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda/conda-bld/playwright_1730983595220/_build_env


The following NEW packages will be INSTALLED:

    _libgcc_mutex:                 0.1-conda_forge           conda-forge
    _openmp_mutex:                 4.5-2_gnu                 conda-forge
    binutils_impl_linux-aarch64:   2.43-h15a6ed9_2           conda-forge
    bzip2:                         1.0.8-h4bc722e_7          conda-forge
    ca-certificates:               2024.8.30-hbcca054_0      conda-forge
    cross-python_linux-aarch64:    3.13-50_cp313             conda-forge
    crossenv:                      1.5.0-pyhd8ed1ab_1        conda-forge
    gcc_impl_linux-aarch64:        14.2.0-hfe1696b_1         conda-forge
    gxx_impl_linux-aarch64:        14.2.0-h0a8fb04_1         conda-forge
    kernel-headers_linux-aarch64:  4.18.0-h05a177a_18        conda-forge
    ld_impl_linux-64:              2.43-h712a8e2_2           conda-forge
    ld_impl_linux-aarch64:         2.43-h0a21ee1_2           conda-forge
    libexpat:                      2.6.4-h5888daf_0          conda-forge
    libffi:                        3.4.2-h7f98852_5          conda-forge
    libgcc:                        14.2.0-h77fa898_1         conda-forge
    libgcc-devel_linux-aarch64:    14.2.0-h3d07465_1         conda-forge
    libgcc-ng:                     14.2.0-h69a702a_1         conda-forge
    libgomp:                       14.2.0-h77fa898_1         conda-forge
    libiconv:                      1.17-hd590300_2           conda-forge
    libmpdec:                      4.0.0-h4bc722e_0          conda-forge
    libsqlite:                     3.47.0-hadc24fc_1         conda-forge
    libstdcxx:                     14.2.0-hc0a3c3a_1         conda-forge
    libstdcxx-devel_linux-aarch64: 14.2.0-h3d07465_1         conda-forge
    libstdcxx-ng:                  14.2.0-h4852527_1         conda-forge
    libuuid:                       2.38.1-h0b41bf4_0         conda-forge
    libzlib:                       1.3.1-hb9d3cd8_2          conda-forge
    lz4-c:                         1.9.4-hcb278e6_0          conda-forge
    ncurses:                       6.5-he02047a_1            conda-forge
    openssl:                       3.3.2-hb9d3cd8_0          conda-forge
    pip:                           24.3.1-pyh145f28c_0       conda-forge
    popt:                          1.16-h0b475e3_2002        conda-forge
    python:                        3.13.0-h9ebbce0_100_cp313 conda-forge
    python_abi:                    3.13-5_cp313              conda-forge
    readline:                      8.2-h8228510_1            conda-forge
    rsync:                         3.3.0-he6cb5fe_0          conda-forge
    sed:                           4.8-he412f7d_0            conda-forge
    sysroot_linux-aarch64:         2.17-h5b4a56d_18          conda-forge
    tk:                            8.6.13-noxft_h4845f30_101 conda-forge
    tzdata:                        2024b-hc8b5060_0          conda-forge
    xxhash:                        0.8.2-hd590300_0          conda-forge
    xz:                            5.2.6-h166bdaf_0          conda-forge
    zstd:                          1.5.6-ha6fb4c9_0          conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
source tree in: /opt/conda/conda-bld/playwright_1730983595220/work
export PREFIX=/opt/conda/conda-bld/playwright_1730983595220/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
export BUILD_PREFIX=/opt/conda/conda-bld/playwright_1730983595220/_build_env
export SRC_DIR=/opt/conda/conda-bld/playwright_1730983595220/work
INFO: activate-binutils_linux-aarch64.sh made the following environmental changes:
+ADDR2LINE=/opt/conda/bin/aarch64-conda-linux-gnu-addr2line
+AR=/opt/conda/bin/aarch64-conda-linux-gnu-ar
+AS=/opt/conda/bin/aarch64-conda-linux-gnu-as
+CXXFILT=/opt/conda/bin/aarch64-conda-linux-gnu-c++filt
+DWP=/opt/conda/bin/aarch64-conda-linux-gnu-dwp
+ELFEDIT=/opt/conda/bin/aarch64-conda-linux-gnu-elfedit
+GPROF=/opt/conda/bin/aarch64-conda-linux-gnu-gprof
+LD=/opt/conda/bin/aarch64-conda-linux-gnu-ld
+LD_GOLD=/opt/conda/bin/aarch64-conda-linux-gnu-ld.gold
+NM=/opt/conda/bin/aarch64-conda-linux-gnu-nm
+OBJCOPY=/opt/conda/bin/aarch64-conda-linux-gnu-objcopy
+OBJDUMP=/opt/conda/bin/aarch64-conda-linux-gnu-objdump
+RANLIB=/opt/conda/bin/aarch64-conda-linux-gnu-ranlib
+READELF=/opt/conda/bin/aarch64-conda-linux-gnu-readelf
+SIZE=/opt/conda/bin/aarch64-conda-linux-gnu-size
+STRINGS=/opt/conda/bin/aarch64-conda-linux-gnu-strings
+STRIP=/opt/conda/bin/aarch64-conda-linux-gnu-strip
INFO: activate-gcc_linux-aarch64.sh made the following environmental changes:
+BUILD=x86_64-conda-linux-gnu
+CC=/opt/conda/bin/aarch64-conda-linux-gnu-cc
+CC_FOR_BUILD=/opt/conda/bin/x86_64-conda-linux-gnu-cc
+CFLAGS=-ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/playwright-1.48.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+CMAKE_ARGS=-DCMAKE_AR=/opt/conda/bin/aarch64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=/opt/conda/bin/aarch64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=/opt/conda/bin/aarch64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=/opt/conda/bin/aarch64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=/opt/conda/bin/aarch64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=/opt/conda/bin/aarch64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=/opt/conda/bin/aarch64-conda-linux-gnu-ld -DCMAKE_STRIP=/opt/conda/bin/aarch64-conda-linux-gnu-strip -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH=$PREFIX;$BUILD_PREFIX/aarch64-conda-linux-gnu/sysroot -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_PROGRAM_PATH=$BUILD_PREFIX/bin;$PREFIX/bin -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=aarch64
+CMAKE_PREFIX_PATH=$PREFIX:/opt/conda/aarch64-conda-linux-gnu/sysroot/usr
+CONDA_BUILD_CROSS_COMPILATION=1
+CONDA_BUILD_SYSROOT=/opt/conda/aarch64-conda-linux-gnu/sysroot
+CONDA_TOOLCHAIN_BUILD=x86_64-conda-linux-gnu
+CONDA_TOOLCHAIN_HOST=aarch64-conda-linux-gnu
+CPP=/opt/conda/bin/aarch64-conda-linux-gnu-cpp
+CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include
+DEBUG_CFLAGS=-ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/playwright-1.48.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem $PREFIX/include
+GCC=/opt/conda/bin/aarch64-conda-linux-gnu-gcc
+GCC_AR=/opt/conda/bin/aarch64-conda-linux-gnu-gcc-ar
+GCC_NM=/opt/conda/bin/aarch64-conda-linux-gnu-gcc-nm
+GCC_RANLIB=/opt/conda/bin/aarch64-conda-linux-gnu-gcc-ranlib
+HOST=aarch64-conda-linux-gnu
+LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
+MESON_ARGS=--buildtype release --prefix=$PREFIX -Dlibdir=lib --cross-file /opt/conda/meson_cross_file.txt
+QEMU_LD_PREFIX=/opt/conda/aarch64-conda-linux-gnu/sysroot
+_CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_aarch64_conda_cos7_linux_gnu
+build_alias=x86_64-conda-linux-gnu
+host_alias=aarch64-conda-linux-gnu
-BUILD=x86_64-conda_cos6-linux-gnu
Setting up cross-python
ERROR: [Errno 2] No such file or directory: '/opt/conda/conda-bld/playwright_1730983595220/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.12/_sysconfigdata_aarch64_conda_cos7_linux_gnu.py'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.12/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.12/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 172, in do_call
        result = plugin_subcommand.action(getattr(args, "_args", args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.12/site-packages/conda_build/plugin.py", line 14, in build
        return execute(args)
               ^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.12/site-packages/conda_build/cli/main_build.py", line 581, in execute
        api.build(
      File "/opt/conda/lib/python3.12/site-packages/conda_build/api.py", line 255, in build
        return build_tree(
               ^^^^^^^^^^^
      File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3782, in build_tree
        packages_from_this = build(
                             ^^^^^^
      File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 2654, in build
        utils.check_call_env(
      File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 406, in check_call_env
        return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 382, in _func_defaulting_env_to_os_environ
        raise subprocess.CalledProcessError(proc.returncode, _args)
    subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/playwright_1730983595220/work/conda_build.sh']' returned non-zero exit status 1.

`$ /opt/conda/bin/conda build --user microsoft . -m conda_build_config_linux_aarch64.yaml`

  environment variables:
                 CIO_TEST=<not set>
    CONDA_ALLOW_SOFTLINKS=false
                CONDA_DIR=/opt/conda
               CONDA_ROOT=/opt/conda
             CONDA_SCRIPT=/opt/conda/etc/profile.d/conda.sh
           CURL_CA_BUNDLE=<not set>
                 GEM_PATH=/usr/local/rvm/gems/ruby-3.3.4:/usr/local/rvm/gems/ruby-3.3.4@global
                   GOPATH=/go
          JUPYTERLAB_PATH=/home/codespace/.local/bin
               LD_PRELOAD=<not set>
                     PATH=/usr/local/rvm/gems/ruby-3.3.4/bin:/usr/local/rvm/gems/ruby-
                          3.3.4@global/bin:/usr/local/rvm/rubies/ruby-
                          3.3.4/bin:/vscode/bin/linux-
                          x64/65edc4939843c90c34d61f4ce11704f09d3e5cb6/bin/remote-cli:/home/code
                          space/.local/bin:/home/codespace/.dotnet:/home/codespace/nvm/current/b
                          in:/home/codespace/.php/current/bin:/home/codespace/.python/current/bi
                          n:/home/codespace/java/current/bin:/home/codespace/.ruby/current/bin:/
                          home/codespace/.local/bin:/usr/local/python/current/bin:/usr/local/py-
                          utils/bin:/usr/local/oryx:/usr/local/go/bin:/go/bin:/usr/local/sdkman/
                          bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/ca
                          ndidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current
                          /bin:/usr/local/sdkman/candidates/ant/current/bin:/usr/local/rvm/gems/
                          default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubi
                          es/default/bin:/usr/local/share/rbenv/bin:/usr/local/php/current/bin:/
                          opt/conda/bin:/usr/local/nvs:/usr/local/share/nvm/versions/node/v20.17
                          .0/bin:/usr/local/hugo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/u
                          sr/bin:/sbin:/bin:/usr/share/dotnet:/home/codespace/.dotnet/tools:/usr
                          /local/rvm/bin
                 PHP_PATH=/usr/local/php/current
         PYTHONIOENCODING=UTF-8
              PYTHON_PATH=/usr/local/python/current
              PYTHON_ROOT=/home/codespace/.python
       REQUESTS_CA_BUNDLE=<not set>
                 RVM_PATH=/usr/local/rvm
            SSL_CERT_FILE=<not set>
             rvm_bin_path=/usr/local/rvm/bin
                 rvm_path=/usr/local/rvm

     active environment : None
       user config file : /home/codespace/.condarc
 populated config files : /home/codespace/.condarc
          conda version : 24.1.2
    conda-build version : 24.1.2
         python version : 3.12.2.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=24.1.2=0
                          __glibc=2.31=0
                          __linux=6.5.0=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/microsoft/linux-64
                          https://conda.anaconda.org/microsoft/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/codespace/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/codespace/.conda/envs
               platform : linux-64
             user-agent : conda/24.1.2 requests/2.32.3 CPython/3.12.2 Linux/6.5.0-1025-azure ubuntu/20.04.6 glibc/2.31 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

**Comment by isuruf** [comment]
Following should work:
```bash
git clone https://github.com/microsoft/playwright-python
cd playwright-python
conda install anaconda-client conda-build conda-verify
conda build --user microsoft . -m conda_build_config_linux_aarch64.yaml
```

**Comment by mxschmitt** [comment]
Appreciate a ton! works 💯
